"""add_ai_flow_to_training

Revision ID: 042756eb2978
Revises: f397b0a48f62
Create Date: 2025-08-10 23:11:54.405029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '042756eb2978'
down_revision = 'f397b0a48f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('ai_flow', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'ai_flow')
    # ### end Alembic commands ###
