"""add_frame_config_table

Revision ID: 0b4d0ef2e3c3
Revises: b913a1d2c013
Create Date: 2025-08-25 18:51:17.363715

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0b4d0ef2e3c3'
down_revision = 'b913a1d2c013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameconfig',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('training_section_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('object_position_x', sa.Float(), nullable=False),
    sa.Column('object_position_y', sa.Float(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('transform_origin_x', sa.Float(), nullable=False),
    sa.Column('transform_origin_y', sa.Float(), nullable=False),
    sa.Column('transition_duration', sa.Float(), nullable=False),
    sa.Column('transition_easing', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['training_section_id'], ['trainingsection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('overlay', sa.Column('frame_config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'overlay', 'frameconfig', ['frame_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'overlay', type_='foreignkey')
    op.drop_column('overlay', 'frame_config_id')
    op.drop_table('frameconfig')
    # ### end Alembic commands ###
