"""remove_style_column_from_overlay

Revision ID: 2219d44e3ff1
Revises: dae6494a6bc9
Create Date: 2025-08-12 18:24:32.414115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2219d44e3ff1'
down_revision = 'dae6494a6bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overlay', 'style')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overlay', sa.Column('style', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
