"""Add icon field to overlay table

Revision ID: 3ad449cc4eba
Revises: 2219d44e3ff1
Create Date: 2025-08-13 15:19:22.053293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad449cc4eba'
down_revision = '2219d44e3ff1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overlay', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overlay', 'icon')
    # ### end Alembic commands ###
