"""Update foreign key constraints for ChatMessage and UserInteraction

Revision ID: 4f514390b69c
Revises: 089b572b3beb
Create Date: 2025-10-03 18:31:39.516415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f514390b69c'
down_revision = '089b572b3beb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, clean up orphaned records that reference non-existent sessions
    op.execute("DELETE FROM chatmessage WHERE session_id NOT IN (SELECT id FROM interactionsession)")
    op.execute("DELETE FROM interactionlog WHERE session_id NOT IN (SELECT id FROM interactionsession)")
    op.execute("DELETE FROM userinteraction WHERE session_id NOT IN (SELECT id FROM interactionsession)")
    
    # Now update the foreign key constraints
    op.drop_constraint('chatmessage_session_id_fkey', 'chatmessage', type_='foreignkey')
    op.create_foreign_key(None, 'chatmessage', 'interactionsession', ['session_id'], ['id'])
    op.drop_constraint('interactionlog_session_id_fkey', 'interactionlog', type_='foreignkey')
    op.create_foreign_key(None, 'interactionlog', 'interactionsession', ['session_id'], ['id'])
    op.drop_constraint('userinteraction_session_id_fkey', 'userinteraction', type_='foreignkey')
    op.create_foreign_key(None, 'userinteraction', 'interactionsession', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userinteraction', type_='foreignkey')
    op.create_foreign_key('userinteraction_session_id_fkey', 'userinteraction', 'session', ['session_id'], ['id'])
    op.drop_constraint(None, 'interactionlog', type_='foreignkey')
    op.create_foreign_key('interactionlog_session_id_fkey', 'interactionlog', 'session', ['session_id'], ['id'])
    op.drop_constraint(None, 'chatmessage', type_='foreignkey')
    op.create_foreign_key('chatmessage_session_id_fkey', 'chatmessage', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###
