"""add_type_to_training_section

Revision ID: 57cfc3aa913a
Revises: 0018
Create Date: 2025-09-13 23:53:31.350599

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '57cfc3aa913a'
down_revision = '0018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingsection', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='video'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingsection', 'type')
    # ### end Alembic commands ###
