"""add_image_url_to_avatar

Revision ID: 61ee9862f0a4
Revises: 57cfc3aa913a
Create Date: 2025-09-14 14:58:09.419255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '61ee9862f0a4'
down_revision = '57cfc3aa913a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    op.add_column('avatar', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Skip the company_id NOT NULL constraint for now - it has null values
    # op.alter_column('companytraining', 'company_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip the company_id constraint change
    # op.alter_column('companytraining', 'company_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    op.drop_column('avatar', 'image_url')
    op.create_table('organization',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_pkey')
    )
    # ### end Alembic commands ###
