"""add_company_id_to_style

Revision ID: 7e7d2250af71
Revises: 0016
Create Date: 2025-09-07 18:12:30.924409

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7e7d2250af71'
down_revision = '0016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('organization')
    op.add_column('asset', sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('asset_organization_id_fkey', 'asset', type_='foreignkey')
    op.create_foreign_key(None, 'asset', 'company', ['company_id'], ['id'])
    op.drop_column('asset', 'organization_id')
    op.add_column('companytraining', sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('companytraining_organization_id_fkey', 'companytraining', type_='foreignkey')
    op.create_foreign_key(None, 'companytraining', 'company', ['company_id'], ['id'])
    op.drop_column('companytraining', 'organization_id')
    op.add_column('flow', sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('flow_organization_id_fkey', 'flow', type_='foreignkey')
    op.create_foreign_key(None, 'flow', 'company', ['company_id'], ['id'])
    op.drop_column('flow', 'organization_id')
    op.add_column('frameconfig', sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('frameconfig_organization_id_fkey', 'frameconfig', type_='foreignkey')
    op.create_foreign_key(None, 'frameconfig', 'company', ['company_id'], ['id'])
    op.drop_column('frameconfig', 'organization_id')
    op.add_column('globalframeconfig', sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('globalframeconfig_organization_id_fkey', 'globalframeconfig', type_='foreignkey')
    op.create_foreign_key(None, 'globalframeconfig', 'company', ['company_id'], ['id'])
    op.drop_column('globalframeconfig', 'organization_id')
    op.add_column('style', sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('style_organization_id_fkey', 'style', type_='foreignkey')
    op.create_foreign_key(None, 'style', 'company', ['company_id'], ['id'])
    op.drop_column('style', 'organization_id')
    op.add_column('training', sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('training_organization_id_fkey', 'training', type_='foreignkey')
    op.create_foreign_key(None, 'training', 'company', ['company_id'], ['id'])
    op.drop_column('training', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.create_foreign_key('training_organization_id_fkey', 'training', 'organization', ['organization_id'], ['id'])
    op.drop_column('training', 'company_id')
    op.add_column('style', sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'style', type_='foreignkey')
    op.create_foreign_key('style_organization_id_fkey', 'style', 'organization', ['organization_id'], ['id'])
    op.drop_column('style', 'company_id')
    op.add_column('globalframeconfig', sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'globalframeconfig', type_='foreignkey')
    op.create_foreign_key('globalframeconfig_organization_id_fkey', 'globalframeconfig', 'organization', ['organization_id'], ['id'])
    op.drop_column('globalframeconfig', 'company_id')
    op.add_column('frameconfig', sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'frameconfig', type_='foreignkey')
    op.create_foreign_key('frameconfig_organization_id_fkey', 'frameconfig', 'organization', ['organization_id'], ['id'])
    op.drop_column('frameconfig', 'company_id')
    op.add_column('flow', sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'flow', type_='foreignkey')
    op.create_foreign_key('flow_organization_id_fkey', 'flow', 'organization', ['organization_id'], ['id'])
    op.drop_column('flow', 'company_id')
    op.add_column('companytraining', sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'companytraining', type_='foreignkey')
    op.create_foreign_key('companytraining_organization_id_fkey', 'companytraining', 'organization', ['organization_id'], ['id'])
    op.drop_column('companytraining', 'company_id')
    op.add_column('asset', sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.create_foreign_key('asset_organization_id_fkey', 'asset', 'organization', ['organization_id'], ['id'])
    op.drop_column('asset', 'company_id')
    op.create_table('organization',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_pkey')
    )
    # ### end Alembic commands ###
