"""Add interaction session models

Revision ID: 9e7d858adfba
Revises: fb778e1b34b0
Create Date: 2025-09-17 11:42:53.924832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = '9e7d858adfba'
down_revision = 'fb778e1b34b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactionsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('training_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_section_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('total_time_spent', sa.Integer(), nullable=False),
    sa.Column('interactions_count', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('llm_context_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['current_section_id'], ['trainingsection.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactionmessage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_context_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_response_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('suggestions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interactionsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectionprogress',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('interactions_count', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('section_data_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['trainingsection.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interactionsession.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # First, update NULL company_id values to a default company
    op.execute("UPDATE companytraining SET company_id = (SELECT id FROM company WHERE is_system = true LIMIT 1) WHERE company_id IS NULL")
    op.alter_column('companytraining', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('session', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('session', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_foreign_key(None, 'session', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.alter_column('session', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('session', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companytraining', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('sectionprogress')
    op.drop_table('interactionmessage')
    op.drop_table('interactionsession')
    # ### end Alembic commands ###
