"""Add icon_style_id to overlay table

Revision ID: aa06ab9f0395
Revises: c77bc62f6123
Create Date: 2025-08-25 21:41:42.957627

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'aa06ab9f0395'
down_revision = 'c77bc62f6123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overlay', sa.Column('icon_style_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'overlay', 'style', ['icon_style_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'overlay', type_='foreignkey')
    op.drop_column('overlay', 'icon_style_id')
    # ### end Alembic commands ###
