"""add_global_frame_config_table

Revision ID: c77bc62f6123
Revises: 0b4d0ef2e3c3
Create Date: 2025-08-25 20:45:56.512439

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c77bc62f6123'
down_revision = '0b4d0ef2e3c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalframeconfig',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('object_position_x', sa.Float(), nullable=False),
    sa.Column('object_position_y', sa.Float(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('transform_origin_x', sa.Float(), nullable=False),
    sa.Column('transform_origin_y', sa.Float(), nullable=False),
    sa.Column('transition_duration', sa.Float(), nullable=False),
    sa.Column('transition_easing', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('frameconfig', sa.Column('global_config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'frameconfig', 'globalframeconfig', ['global_config_id'], ['id'])
    op.add_column('overlay', sa.Column('frame_config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'overlay', 'frameconfig', ['frame_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'overlay', type_='foreignkey')
    op.drop_column('overlay', 'frame_config_id')
    op.drop_constraint(None, 'frameconfig', type_='foreignkey')
    op.drop_column('frameconfig', 'global_config_id')
    op.drop_table('globalframeconfig')
    # ### end Alembic commands ###
