"""Add user interaction tracking tables

Revision ID: e124230fe326
Revises: 61ee9862f0a4
Create Date: 2025-09-14 17:10:07.110174

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import sql


# revision identifiers, used by Alembic.
revision = 'e124230fe326'
down_revision = '61ee9862f0a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmessage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('video_time', sa.Float(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('llm_response_time', sa.Float(), nullable=True),
    sa.Column('audio_data', sa.String(), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('message_metadata', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['trainingsection.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainingprogress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('current_section_id', sa.String(), nullable=True),
    sa.Column('completed_sections', sa.String(), nullable=False),
    sa.Column('current_video_time', sa.Float(), nullable=True),
    sa.Column('total_time_spent', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('first_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('sections_attempted', sa.Integer(), nullable=False),
    sa.Column('sections_completed', sa.Integer(), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('chat_messages_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['current_section_id'], ['trainingsection.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinteraction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('overlay_id', sa.String(), nullable=True),
    sa.Column('video_time', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('interaction_metadata', sa.String(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['overlay_id'], ['overlay.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['trainingsection.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('companytraining', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('session', sa.Column('company_id', sa.String(), nullable=True))
    op.add_column('session', sa.Column('last_activity_at', sa.DateTime(), nullable=False))
    op.add_column('session', sa.Column('total_duration', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('completion_percentage', sa.Float(), nullable=True))
    op.add_column('session', sa.Column('status', sa.String(), nullable=False))
    op.create_foreign_key(None, 'session', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'status')
    op.drop_column('session', 'completion_percentage')
    op.drop_column('session', 'total_duration')
    op.drop_column('session', 'last_activity_at')
    op.drop_column('session', 'company_id')
    op.alter_column('companytraining', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('userinteraction')
    op.drop_table('trainingprogress')
    op.drop_table('chatmessage')
    # ### end Alembic commands ###
