"""add_duration_to_overlay

Revision ID: f397b0a48f62
Revises: 0010_fix_overlay_missing_columns
Create Date: 2025-08-10 22:41:06.136117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f397b0a48f62'
down_revision = '0010_fix_overlay_missing_columns'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overlay', sa.Column('duration', sa.Float(), nullable=True))
    
    # Update existing null time_stamp values to 0
    op.execute("UPDATE overlay SET time_stamp = 0 WHERE time_stamp IS NULL")
    op.alter_column('overlay', 'time_stamp',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # Update existing null type values to 'label'
    op.execute("UPDATE overlay SET type = 'label' WHERE type IS NULL")
    op.alter_column('overlay', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'User'::character varying"))
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'User'::character varying"))
    op.alter_column('overlay', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('overlay', 'time_stamp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('overlay', 'duration')
    # ### end Alembic commands ###
