"""Add agent_id field to TrainingSection

Revision ID: fb778e1b34b0
Revises: e124230fe326
Create Date: 2025-09-17 09:30:54.235187

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb778e1b34b0'
down_revision = 'e124230fe326'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add agent_id field to trainingsection table
    op.add_column('trainingsection', sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove agent_id field from trainingsection table
    op.drop_column('trainingsection', 'agent_id')
    # ### end Alembic commands ###
