"""add_agent_conversation_logging

Revision ID: fcfb2db8523f
Revises: f8db4719bcb5
Create Date: 2025-09-28 23:06:40.881193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfb2db8523f'
down_revision = 'f8db4719bcb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
