"""Add elevenlabs conversation tracking to InteractionSession

Revision ID: fda175a6da75
Revises: 4f514390b69c
Create Date: 2025-10-03 21:19:37.004906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda175a6da75'
down_revision = '4f514390b69c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactionsession', sa.Column('elevenlabs_conversation_id', sa.String(), nullable=True))
    op.add_column('interactionsession', sa.Column('elevenlabs_agent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactionsession', 'elevenlabs_agent_id')
    op.drop_column('interactionsession', 'elevenlabs_conversation_id')
    # ### end Alembic commands ###
