name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install root deps
        run: npm ci

      - name: Install web deps
        working-directory: apps/web
        run: npm ci

      - name: Lint web
        working-directory: apps/web
        run: npm run lint

      - name: Build web
        working-directory: apps/web
        run: npm run build

      - name: Install api deps
        working-directory: apps/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint api
        working-directory: apps/api
        run: |
          python -m pip install flake8
          flake8 app || true

      - name: Type check api
        working-directory: apps/api
        run: |
          python -m pip install mypy
          mypy app || true

      - name: Build api
        working-directory: apps/api
        run: |
          python -m py_compile $(git ls-files '*.py')
